---
booktitle: Proceedings of the Workshop on On-line Trading of Exploration and Exploitation
  2
publisher: JMLR Workshop and Conference Proceedings
logoright: SAIS_logo.jpg
volume: 26
year: '2011'
start: 2011-07-02
end: 2011-07-02
published: 2012-05-02
month: 0
shortname: On-line Trading of Exploration and Exploitation 2
sections:
- name: preface
  title: Preface
- name: default
  title: Accepted Papers
layout: proceedings
series: Proceedings of Machine Learning Research
id: GlowackaExploitation2011
abstract: ''
editor:
- given: Dorota
  family: Glowacka
- given: Louis
  family: Dorard
- given: John
  family: Shawe-Taylor
title: Proceedings of the Workshop on On-line Trading of Exploration and Exploitation
  2
email: ''
description: Proceedings of the Workshop on On-line Trading of Exploration and Exploitation
  2, Bellevue, Washington, USA
url: http://proceedings.mlr.press
baseurl: "/v26"
twitter_username: mlresearch
github_username: mlresearch
markdown: kramdown
permalink: "/:title.html"
github:
  edit: true
  repository: v26
conference:
  name: Proceedings of the Workshop on On-line Trading of Exploration and Exploitation
    2
  url: 
  location: Bellevue, Washington, USA
  dates:
  - 2011-07-02
analytics:
  google:
    tracking_id: UA-92432422-1
# Site settings
# Auto generated from v26.bib
