---
booktitle: Proceedings of the Workshop on On-line Trading of Exploration and Exploitation
  2
orig_bibfile: "/Users/neil/mlresearch/bibtex.bib"
publisher: JMLR Workshop and Conference Proceedings
volume: 26
year: '2011'
start: 2011-07-02
end: 2011-07-02
published: 2012-05-02
month: 0
shortname: On-line Trading of Exploration and Exploitation 2
sections:
- name: preface
  title: Preface
- name: default
  title: Accepted Papers
layout: proceedings
series: Proceedings of Machine Learning Research
issn: 1938-7228
id: GlowackaExploitation2011
cycles: false
editor:
- given: Dorota
  family: Glowacka
- given: Louis
  family: Dorard
- given: John
  family: Shawe-Taylor
title: Proceedings of Machine Learning Research
description: |
  Proceedings of the Workshop on On-line Trading of Exploration and Exploitation 2
    Held in Bellevue, Washington, USA on 02 July 2011

  Published as Volume 26 by the Proceedings of Machine Learning Research on 02 May 2012.

  Volume Edited by:
    Dorota Glowacka
    Louis Dorard
    John Shawe-Taylor

  Series Editors:
    Neil D. Lawrence
date_str: 02 Jul
url: http://proceedings.mlr.press
author:
  name: PMLR
baseurl: "/v26"
twitter_username: MLResearchPress
github_username: mlresearch
markdown: kramdown
exclude:
- README.md
- Gemfile
- ".gitignore"
style: pmlr
plugins:
- jekyll-feed
- jekyll-seo-tag
- jekyll-remote-theme
remote_theme: lawrennd/proceedings
permalink: "/:title.html"
ghub:
  edit: true
  repository: v26
display:
  copy_button:
    bibtex: true
    endnote: true
    apa: true
    ris: true
  comments: false
email: ''
conference:
  name: Proceedings of the Workshop on On-line Trading of Exploration and Exploitation
    2
  url: 
  location: Bellevue, Washington, USA
  dates:
  - 2011-07-02
  number: 2
analytics:
  google:
    tracking_id: UA-92432422-1
# Site settings
# Original source:  /Users/neil/mlresearch/bibtex.bib
